name: SIT
favicon: null
layout_spectrum: 0.75449
typography_spectrum: 0.20402
title: Solutions For Innovative Technology GmbH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#56b03b'
    - '#ffffff'
    - '#777777'
    - '#ababab'
  brandStrength: 0.7650347438175231
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
