name: SIT
favicon: null
layout_spectrum: 0.30620355322025716
typography_spectrum: 0.20603136206045747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7650347438175231
  lightness: 0.44893433107063174
  saturation: 0.4898817064240575
  rhythmicContrast: 0.4861395573243499
purpose: []
