typography_spectrum: 0.51271
color:
  brandColors:
    - '#1d1d1d'
    - '#56b03b'
    - '#ffffff'
    - '#777777'
    - '#ababab'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51122
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Sven Wiese-Solty
  email: s.wiese-solty@sforit.de
  url: www.sforit.de
name: SIT
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Solutions For Innovative Technology GmbH
purpose: []
